name: Build

on:
  workflow_dispatch: 
  push:
    branches: 
      - 'master'
  pull_request:
    branches: 
      - '*'
      - '*/*'
      - '**'

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Generate build files
        run: mkdir build && cd build && cmake ../src -G "Visual Studio 16 2019" -A Win32

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'websockets-win'
          path: build/bin/Release

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib libstdc++6:i386 libc6:i386

      - name: Generate build files
        run: mkdir build && cd build && cmake ../src

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Rename file
        run: |
          cd build/lib
          mv libpawn-websockets.so pawn-websockets.so

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'websockets-linux'
          path: build/lib