name: Build

on:
  workflow_dispatch: 
  push:
    branches: 
      - 'master'
  pull_request:
    branches: 
      - '*'
      - '*/*'
      - '**'

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Generate build files
        run: mkdir build && cd build && cmake ../src -G "Visual Studio 16 2019" -A Win32

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'websockets-win'
          path: build/bin/Release

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create artifact directory
        run: mkdir artifact

      - name: Build
        run: |
          cd docker
          chmod +x ./build.sh
          chmod +x ./docker-entrypoint.sh
          ./build.sh

      - name: Move file
        run: |
          cp docker/build/lib/libpawn-websockets.so artifact/pawn-websockets.so

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'websockets-linux'
          path: artifact